// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.v2.storage.blob.models;

import io.clientcore.core.utils.ExpandableEnum;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Function;

/**
 * Defines values for BlobDeleteType.
 */
public final class BlobDeleteType implements ExpandableEnum<String> {
    private static final Map<String, BlobDeleteType> VALUES = new ConcurrentHashMap<>();

    private static final Function<String, BlobDeleteType> NEW_INSTANCE = BlobDeleteType::new;

    /**
     * Static value Permanent for BlobDeleteType.
     */
    public static final BlobDeleteType PERMANENT = fromValue("Permanent");

    private final String value;

    private BlobDeleteType(String value) {
        this.value = value;
    }

    /**
     * Creates or finds a BlobDeleteType.
     * 
     * @param value a value to look for.
     * @return the corresponding BlobDeleteType.
     * @throws IllegalArgumentException if value is null.
     */
    public static BlobDeleteType fromValue(String value) {
        if (value == null) {
            throw new IllegalArgumentException("'value' cannot be null.");
        }
        return VALUES.computeIfAbsent(value, NEW_INSTANCE);
    }

    /**
     * Gets known BlobDeleteType values.
     * 
     * @return Known BlobDeleteType values.
     */
    public static Collection<BlobDeleteType> values() {
        return new ArrayList<>(VALUES.values());
    }

    /**
     * Gets the value of the BlobDeleteType instance.
     * 
     * @return the value of the BlobDeleteType instance.
     */
    @Override
    public String getValue() {
        return this.value;
    }

    @Override
    public String toString() {
        return Objects.toString(this.value);
    }

    @Override
    public boolean equals(Object obj) {
        return this == obj;
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(this.value);
    }
}
