// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.v2.storage.blob.models;

import io.clientcore.core.utils.ExpandableEnum;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Function;

/**
 * The status of the secondary location.
 */
public final class GeoReplicationStatus implements ExpandableEnum<String> {
    private static final Map<String, GeoReplicationStatus> VALUES = new ConcurrentHashMap<>();

    private static final Function<String, GeoReplicationStatus> NEW_INSTANCE = GeoReplicationStatus::new;

    /**
     * Static value live for GeoReplicationStatus.
     */
    public static final GeoReplicationStatus LIVE = fromValue("live");

    /**
     * Static value bootstrap for GeoReplicationStatus.
     */
    public static final GeoReplicationStatus BOOTSTRAP = fromValue("bootstrap");

    /**
     * Static value unavailable for GeoReplicationStatus.
     */
    public static final GeoReplicationStatus UNAVAILABLE = fromValue("unavailable");

    private final String value;

    private GeoReplicationStatus(String value) {
        this.value = value;
    }

    /**
     * Creates or finds a GeoReplicationStatus.
     * 
     * @param value a value to look for.
     * @return the corresponding GeoReplicationStatus.
     * @throws IllegalArgumentException if value is null.
     */
    public static GeoReplicationStatus fromValue(String value) {
        if (value == null) {
            throw new IllegalArgumentException("'value' cannot be null.");
        }
        return VALUES.computeIfAbsent(value, NEW_INSTANCE);
    }

    /**
     * Gets known GeoReplicationStatus values.
     * 
     * @return Known GeoReplicationStatus values.
     */
    public static Collection<GeoReplicationStatus> values() {
        return new ArrayList<>(VALUES.values());
    }

    /**
     * Gets the value of the GeoReplicationStatus instance.
     * 
     * @return the value of the GeoReplicationStatus instance.
     */
    @Override
    public String getValue() {
        return this.value;
    }

    @Override
    public String toString() {
        return Objects.toString(this.value);
    }

    @Override
    public boolean equals(Object obj) {
        return this == obj;
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(this.value);
    }
}
