// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.v2.storage.blob.models;

import io.clientcore.core.utils.ExpandableEnum;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Function;

/**
 * Defines values for PremiumPageBlobAccessTier.
 */
public final class PremiumPageBlobAccessTier implements ExpandableEnum<String> {
    private static final Map<String, PremiumPageBlobAccessTier> VALUES = new ConcurrentHashMap<>();

    private static final Function<String, PremiumPageBlobAccessTier> NEW_INSTANCE = PremiumPageBlobAccessTier::new;

    /**
     * Static value P4 for PremiumPageBlobAccessTier.
     */
    public static final PremiumPageBlobAccessTier P4 = fromValue("P4");

    /**
     * Static value P6 for PremiumPageBlobAccessTier.
     */
    public static final PremiumPageBlobAccessTier P6 = fromValue("P6");

    /**
     * Static value P10 for PremiumPageBlobAccessTier.
     */
    public static final PremiumPageBlobAccessTier P10 = fromValue("P10");

    /**
     * Static value P15 for PremiumPageBlobAccessTier.
     */
    public static final PremiumPageBlobAccessTier P15 = fromValue("P15");

    /**
     * Static value P20 for PremiumPageBlobAccessTier.
     */
    public static final PremiumPageBlobAccessTier P20 = fromValue("P20");

    /**
     * Static value P30 for PremiumPageBlobAccessTier.
     */
    public static final PremiumPageBlobAccessTier P30 = fromValue("P30");

    /**
     * Static value P40 for PremiumPageBlobAccessTier.
     */
    public static final PremiumPageBlobAccessTier P40 = fromValue("P40");

    /**
     * Static value P50 for PremiumPageBlobAccessTier.
     */
    public static final PremiumPageBlobAccessTier P50 = fromValue("P50");

    /**
     * Static value P60 for PremiumPageBlobAccessTier.
     */
    public static final PremiumPageBlobAccessTier P60 = fromValue("P60");

    /**
     * Static value P70 for PremiumPageBlobAccessTier.
     */
    public static final PremiumPageBlobAccessTier P70 = fromValue("P70");

    /**
     * Static value P80 for PremiumPageBlobAccessTier.
     */
    public static final PremiumPageBlobAccessTier P80 = fromValue("P80");

    private final String value;

    private PremiumPageBlobAccessTier(String value) {
        this.value = value;
    }

    /**
     * Creates or finds a PremiumPageBlobAccessTier.
     * 
     * @param value a value to look for.
     * @return the corresponding PremiumPageBlobAccessTier.
     * @throws IllegalArgumentException if value is null.
     */
    public static PremiumPageBlobAccessTier fromValue(String value) {
        if (value == null) {
            throw new IllegalArgumentException("'value' cannot be null.");
        }
        return VALUES.computeIfAbsent(value, NEW_INSTANCE);
    }

    /**
     * Gets known PremiumPageBlobAccessTier values.
     * 
     * @return Known PremiumPageBlobAccessTier values.
     */
    public static Collection<PremiumPageBlobAccessTier> values() {
        return new ArrayList<>(VALUES.values());
    }

    /**
     * Gets the value of the PremiumPageBlobAccessTier instance.
     * 
     * @return the value of the PremiumPageBlobAccessTier instance.
     */
    @Override
    public String getValue() {
        return this.value;
    }

    @Override
    public String toString() {
        return Objects.toString(this.value);
    }

    @Override
    public boolean equals(Object obj) {
        return this == obj;
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(this.value);
    }
}
