// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.microsoft.azure.cognitiveservices.language.textanalytics.models;

import com.azure.core.implementation.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The DocumentStatistics model.
 */
@Fluent
public final class DocumentStatistics {
    /*
     * Number of text elements recognized in the document.
     */
    @JsonProperty(value = "charactersCount")
    private Integer charactersCount;

    /*
     * Number of transactions for the document.
     */
    @JsonProperty(value = "transactionsCount")
    private Integer transactionsCount;

    /**
     * Get the charactersCount property: Number of text elements recognized in
     * the document.
     *
     * @return the charactersCount value.
     */
    public Integer charactersCount() {
        return this.charactersCount;
    }

    /**
     * Set the charactersCount property: Number of text elements recognized in
     * the document.
     *
     * @param charactersCount the charactersCount value to set.
     * @return the DocumentStatistics object itself.
     */
    public DocumentStatistics charactersCount(Integer charactersCount) {
        this.charactersCount = charactersCount;
        return this;
    }

    /**
     * Get the transactionsCount property: Number of transactions for the
     * document.
     *
     * @return the transactionsCount value.
     */
    public Integer transactionsCount() {
        return this.transactionsCount;
    }

    /**
     * Set the transactionsCount property: Number of transactions for the
     * document.
     *
     * @param transactionsCount the transactionsCount value to set.
     * @return the DocumentStatistics object itself.
     */
    public DocumentStatistics transactionsCount(Integer transactionsCount) {
        this.transactionsCount = transactionsCount;
        return this;
    }
}
