// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.microsoft.azure.cognitiveservices.language.textanalytics.models;

import com.azure.core.implementation.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The EntityRecord model.
 */
@Fluent
public final class EntityRecord {
    /*
     * Entity formal name.
     */
    @JsonProperty(value = "name")
    private String name;

    /*
     * List of instances this entity appears in the text.
     */
    @JsonProperty(value = "matches")
    private List<MatchRecord> matches;

    /*
     * Wikipedia language for which the WikipediaId and WikipediaUrl refers to.
     */
    @JsonProperty(value = "wikipediaLanguage")
    private String wikipediaLanguage;

    /*
     * Wikipedia unique identifier of the recognized entity.
     */
    @JsonProperty(value = "wikipediaId")
    private String wikipediaId;

    /*
     * URL for the entity's Wikipedia page.
     */
    @JsonProperty(value = "wikipediaUrl", access = JsonProperty.Access.WRITE_ONLY)
    private String wikipediaUrl;

    /*
     * Bing unique identifier of the recognized entity. Use in conjunction with
     * the Bing Entity Search API to fetch additional relevant information.
     */
    @JsonProperty(value = "bingId")
    private String bingId;

    /*
     * Entity type from Named Entity Recognition model
     */
    @JsonProperty(value = "type")
    private String type;

    /*
     * Entity sub type from Named Entity Recognition model
     */
    @JsonProperty(value = "subType")
    private String subType;

    /**
     * Get the name property: Entity formal name.
     *
     * @return the name value.
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name property: Entity formal name.
     *
     * @param name the name value to set.
     * @return the EntityRecord object itself.
     */
    public EntityRecord name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the matches property: List of instances this entity appears in the
     * text.
     *
     * @return the matches value.
     */
    public List<MatchRecord> matches() {
        return this.matches;
    }

    /**
     * Set the matches property: List of instances this entity appears in the
     * text.
     *
     * @param matches the matches value to set.
     * @return the EntityRecord object itself.
     */
    public EntityRecord matches(List<MatchRecord> matches) {
        this.matches = matches;
        return this;
    }

    /**
     * Get the wikipediaLanguage property: Wikipedia language for which the
     * WikipediaId and WikipediaUrl refers to.
     *
     * @return the wikipediaLanguage value.
     */
    public String wikipediaLanguage() {
        return this.wikipediaLanguage;
    }

    /**
     * Set the wikipediaLanguage property: Wikipedia language for which the
     * WikipediaId and WikipediaUrl refers to.
     *
     * @param wikipediaLanguage the wikipediaLanguage value to set.
     * @return the EntityRecord object itself.
     */
    public EntityRecord wikipediaLanguage(String wikipediaLanguage) {
        this.wikipediaLanguage = wikipediaLanguage;
        return this;
    }

    /**
     * Get the wikipediaId property: Wikipedia unique identifier of the
     * recognized entity.
     *
     * @return the wikipediaId value.
     */
    public String wikipediaId() {
        return this.wikipediaId;
    }

    /**
     * Set the wikipediaId property: Wikipedia unique identifier of the
     * recognized entity.
     *
     * @param wikipediaId the wikipediaId value to set.
     * @return the EntityRecord object itself.
     */
    public EntityRecord wikipediaId(String wikipediaId) {
        this.wikipediaId = wikipediaId;
        return this;
    }

    /**
     * Get the wikipediaUrl property: URL for the entity's Wikipedia page.
     *
     * @return the wikipediaUrl value.
     */
    public String wikipediaUrl() {
        return this.wikipediaUrl;
    }

    /**
     * Get the bingId property: Bing unique identifier of the recognized
     * entity. Use in conjunction with the Bing Entity Search API to fetch
     * additional relevant information.
     *
     * @return the bingId value.
     */
    public String bingId() {
        return this.bingId;
    }

    /**
     * Set the bingId property: Bing unique identifier of the recognized
     * entity. Use in conjunction with the Bing Entity Search API to fetch
     * additional relevant information.
     *
     * @param bingId the bingId value to set.
     * @return the EntityRecord object itself.
     */
    public EntityRecord bingId(String bingId) {
        this.bingId = bingId;
        return this;
    }

    /**
     * Get the type property: Entity type from Named Entity Recognition model.
     *
     * @return the type value.
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type property: Entity type from Named Entity Recognition model.
     *
     * @param type the type value to set.
     * @return the EntityRecord object itself.
     */
    public EntityRecord type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the subType property: Entity sub type from Named Entity Recognition
     * model.
     *
     * @return the subType value.
     */
    public String subType() {
        return this.subType;
    }

    /**
     * Set the subType property: Entity sub type from Named Entity Recognition
     * model.
     *
     * @param subType the subType value to set.
     * @return the EntityRecord object itself.
     */
    public EntityRecord subType(String subType) {
        this.subType = subType;
        return this;
    }
}
