// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.microsoft.azure.cognitiveservices.language.textanalytics.models;

import com.azure.core.implementation.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ErrorRecord model.
 */
@Fluent
public final class ErrorRecord {
    /*
     * Input document unique identifier the error refers to.
     */
    @JsonProperty(value = "id")
    private String id;

    /*
     * Error message.
     */
    @JsonProperty(value = "message")
    private String message;

    /**
     * Get the id property: Input document unique identifier the error refers
     * to.
     *
     * @return the id value.
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id property: Input document unique identifier the error refers
     * to.
     *
     * @param id the id value to set.
     * @return the ErrorRecord object itself.
     */
    public ErrorRecord id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the message property: Error message.
     *
     * @return the message value.
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the message property: Error message.
     *
     * @param message the message value to set.
     * @return the ErrorRecord object itself.
     */
    public ErrorRecord message(String message) {
        this.message = message;
        return this;
    }
}
