// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.microsoft.azure.cognitiveservices.language.textanalytics.models;

import com.azure.core.implementation.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The KeyPhraseBatchResult model.
 */
@Fluent
public final class KeyPhraseBatchResult {
    /*
     * Response by document
     */
    @JsonProperty(value = "documents", access = JsonProperty.Access.WRITE_ONLY)
    private List<KeyPhraseBatchResultItem> documents;

    /*
     * Errors and Warnings by document
     */
    @JsonProperty(value = "errors", access = JsonProperty.Access.WRITE_ONLY)
    private List<ErrorRecord> errors;

    /*
     * =(Optional) if showStats=true was specified in the request this field
     * will contain information about the request payload.
     */
    @JsonProperty(value = "statistics", access = JsonProperty.Access.WRITE_ONLY)
    private RequestStatistics statistics;

    /**
     * Get the documents property: Response by document.
     *
     * @return the documents value.
     */
    public List<KeyPhraseBatchResultItem> documents() {
        return this.documents;
    }

    /**
     * Get the errors property: Errors and Warnings by document.
     *
     * @return the errors value.
     */
    public List<ErrorRecord> errors() {
        return this.errors;
    }

    /**
     * Get the statistics property: =(Optional) if showStats=true was specified
     * in the request this field will contain information about the request
     * payload.
     *
     * @return the statistics value.
     */
    public RequestStatistics statistics() {
        return this.statistics;
    }
}
