// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.microsoft.azure.cognitiveservices.language.textanalytics.models;

import com.azure.core.implementation.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The KeyPhraseBatchResultItem model.
 */
@Fluent
public final class KeyPhraseBatchResultItem {
    /*
     * Unique, non-empty document identifier.
     */
    @JsonProperty(value = "id")
    private String id;

    /*
     * A list of representative words or phrases. The number of key phrases
     * returned is proportional to the number of words in the input document.
     */
    @JsonProperty(value = "keyPhrases", access = JsonProperty.Access.WRITE_ONLY)
    private List<String> keyPhrases;

    /*
     * (Optional) if showStats=true was specified in the request this field
     * will contain information about the document payload.
     */
    @JsonProperty(value = "statistics")
    private DocumentStatistics statistics;

    /**
     * Get the id property: Unique, non-empty document identifier.
     *
     * @return the id value.
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id property: Unique, non-empty document identifier.
     *
     * @param id the id value to set.
     * @return the KeyPhraseBatchResultItem object itself.
     */
    public KeyPhraseBatchResultItem id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the keyPhrases property: A list of representative words or phrases.
     * The number of key phrases returned is proportional to the number of
     * words in the input document.
     *
     * @return the keyPhrases value.
     */
    public List<String> keyPhrases() {
        return this.keyPhrases;
    }

    /**
     * Get the statistics property: (Optional) if showStats=true was specified
     * in the request this field will contain information about the document
     * payload.
     *
     * @return the statistics value.
     */
    public DocumentStatistics statistics() {
        return this.statistics;
    }

    /**
     * Set the statistics property: (Optional) if showStats=true was specified
     * in the request this field will contain information about the document
     * payload.
     *
     * @param statistics the statistics value to set.
     * @return the KeyPhraseBatchResultItem object itself.
     */
    public KeyPhraseBatchResultItem statistics(DocumentStatistics statistics) {
        this.statistics = statistics;
        return this;
    }
}
